# yaml-language-server: $schema=https://raw.githubusercontent.com/goreleaser/goreleaser/v2.12.7/www/docs/static/schema.json

version: 2

project_name: ip-2-cloudresource

#######################
# Binaries
#######################
before:
  hooks:
    - go mod tidy

builds:
  - binary: ip2cr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

# REF: https://goreleaser.com/customization/universalbinaries/
# universal_binaries:
#   - replace: true

archives:
  - formats: tar.gz
    # use zip for windows archives
    format_overrides:
    - goos: windows
      formats: zip

checksum:
  name_template: "checksums.txt"

#######################
# Docker images
#######################
dockers:
  -
    image_templates:
      # Docker Hub
      - "docker.io/magneticstain/{{.ProjectName}}:latest"
      - "docker.io/magneticstain/{{.ProjectName}}:v{{ .Major }}"
      - "docker.io/magneticstain/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}"
      - "docker.io/magneticstain/{{.ProjectName}}:{{ .Tag }}"
      # GitHub Container Registry
      - "ghcr.io/magneticstain/{{.ProjectName}}:latest"
      - "ghcr.io/magneticstain/{{.ProjectName}}:v{{ .Major }}"
      - "ghcr.io/magneticstain/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/magneticstain/{{.ProjectName}}:{{ .Tag }}"

    dockerfile: "Dockerfile-release"

docker_digest:
  name_template: "digests.txt"

#######################
# Build Artifacts
#######################
sboms:
  - disable: false
  # - artifacts: "any"

report_sizes: true

snapshot:
  version_template: "{{ incpatch .Version }}-next"

# binary_signs:
#   - {}

# signs:
#   - artifacts: all


#######################
# Release
#######################
release:
  github:
    owner: magneticstain
    name: ip-2-cloudresource
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - '^[Dd]eploy: '
      - '^[Mm]inor: '
      - '^[Tt]est: '
      - '^Merge '

homebrew_casks:
  -
    name: ip2cr

    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"

    homepage: "https://github.com/magneticstain/ip-2-cloudresource"
    description: "IP-2-CloudResource: correlate an IP address with its associated cloud resource"

    repository:
      owner: magneticstain
      name: homebrew-ip2cr

      token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"

    commit_author:
      name: magneticstain
      email: magneticstain@gmail.com
      # signing:
      #   enabled: true
      #   key: "{{ .Env.GPG_PRIVATE_KEY }}"
