before:
  hooks:
    - go mod tidy
builds:
  - binary: ip2cr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}_
      {{- .Tag}}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^deploy: '
      - '^minor: '
      - '^test: '
      - '^Merge '
release:
  github:
    owner: magneticstain
    name: ip-2-cloudresource
  prerelease: auto
brews:
  -
    name: ip2cr

    commit_author:
      name: magneticstain
      email: magneticstain@gmail.com

    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    folder: Formula
    homepage: "https://github.com/magneticstain/ip-2-cloudresource"
    description: "IP-2-CloudResource: correlate an IP address with its associated cloud resource"
    license: "MIT"

    test: |
      system "#{bin}/ip2cr --help"

    repository:
      owner: magneticstain
      name: homebrew-ip2cr

      token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"
