# yaml-language-server: $schema=https://raw.githubusercontent.com/goreleaser/goreleaser/v2.12.7/www/docs/static/schema.json

version: 2

project_name: ip-2-cloudresource

before:
  hooks:
    - go mod tidy

builds:
  - binary: ip2cr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      # - arm64

# REF: https://goreleaser.com/customization/universalbinaries/
universal_binaries:
  - replace: true

archives:
  - formats: tar.gz
    meta: true  # includes source code in the archive
    # this name template makes the OS and Arch compatible with the results of uname.
    # name_template: >-
    #   {{ .ProjectName }}_
    #   {{- title .Os }}_
    #   {{- if eq .Arch "amd64" }}x86_64
    #   {{- else if eq .Arch "386" }}i386
    #   {{- else }}{{ .Arch }}{{ end }}
    #   {{- if .Arm }}v{{ .Arm }}{{ end }}_
    #   {{- .Tag}}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      formats: zip

checksum:
  name_template: "checksums.txt"

dockers:
  -
    image_templates:
      # Docker Hub
      - "docker.io/magneticstain/{{.ProjectName}}:latest"
      - "docker.io/magneticstain/{{.ProjectName}}:v{{ .Major }}"
      - "docker.io/magneticstain/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}"
      - "docker.io/magneticstain/{{.ProjectName}}:{{ .Tag }}"
      # GitHub Container Registry
      - "ghcr.io/magneticstain/{{.ProjectName}}:latest"
      - "ghcr.io/magneticstain/{{.ProjectName}}:v{{ .Major }}"
      - "ghcr.io/magneticstain/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/magneticstain/{{.ProjectName}}:{{ .Tag }}"

    dockerfile: "Dockerfile-release"

docker_digest:
  name_template: "digests.txt"

sboms:
  - disable: false
  # - artifacts: "any"

report_sizes: true

# binary_signs:
#   - {}

signs:
  - artifacts: all

# snapshot:
#   name_template: "{{ incpatch .Version }}-next"

release:
  github:
    owner: magneticstain
    name: ip-2-cloudresource
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - '^[Dd]eploy: '
      - '^[Mm]inor: '
      - '^[Tt]est: '
      - '^Merge '

# brews:
#   -
#     name: ip2cr

#     commit_author:
#       name: magneticstain
#       email: magneticstain@gmail.com

#     commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

#     folder: Formula
#     homepage: "https://github.com/magneticstain/ip-2-cloudresource"
#     description: "IP-2-CloudResource: correlate an IP address with its associated cloud resource"
#     license: "MIT"

#     test: |
#       system "#{bin}/ip2cr --help"

#     repository:
#       owner: magneticstain
#       name: homebrew-ip2cr

#       token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"

homebrew_casks:
  -
    name: ip2cr

    commit_author:
      name: magneticstain
      email: magneticstain@gmail.com
      signing:
        enabled: true

    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"

    homepage: "https://github.com/magneticstain/ip-2-cloudresource"
    description: "IP-2-CloudResource: correlate an IP address with its associated cloud resource"

    repository:
      owner: magneticstain
      name: homebrew-ip2cr

      token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"
